#!/bin/python

from mysql.connector import connect
from datetime import datetime, timedelta

import uuid, ssl, sys, os, random, json

db_config = json.load(open("config/database.json", "r"))
db = connect(**db_config, autocommit = True)

query = "INSERT INTO documents (name, date_cre, user_add, user_mod, type_id, path_id, status_id) VALUES(%s, %s, %s, %s, %s, %s, %s)"
cur = db.cursor(prepared = True)
now = datetime.now()

for i in range(1000000):

	name = str(uuid.uuid4())
	cre = now - timedelta(minutes = random.randint(1, 2628000))
	user = 1
	typ = random.randint(1, 4)
	path = random.randint(1, 4)
	stat = random.randint(1, 3)

	cur.execute(query, (name, cre, user, user, typ, path, stat))

